// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: settings.proto
// Protobuf C++ Version: 5.29.5

#include "settings.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Service {
namespace Proto {

inline constexpr LaunchGame::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : usinghoyolabaccount_{false},
        arecommandlineargumentsenabled_{false},
        iswindowshdrenabled_{false},
        isfullscreen_{false},
        isexclusive_{false},
        isborderless_{false},
        isscreenwidthenabled_{false},
        isscreenheightenabled_{false},
        screenwidth_{0},
        screenheight_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LaunchGame::LaunchGame(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LaunchGameDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LaunchGameDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LaunchGameDefaultTypeInternal() {}
  union {
    LaunchGame _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LaunchGameDefaultTypeInternal _LaunchGame_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR Island_ItemsEntry_DoNotUse::Island_ItemsEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Island_ItemsEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : Island_ItemsEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct Island_ItemsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Island_ItemsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Island_ItemsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    Island_ItemsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Island_ItemsEntry_DoNotUseDefaultTypeInternal _Island_ItemsEntry_DoNotUse_default_instance_;

inline constexpr Island::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : items_{},
        fieldofview_{0},
        enablesetfieldofview_{false},
        fixlowfovscene_{false},
        disablefog_{false},
        enablesettargetframerate_{false},
        targetframerate_{0},
        removeopenteamprogress_{false},
        hidequestbanner_{false},
        disableeventcameramove_{false},
        disableshowdamagetext_{false},
        usingtouchscreen_{false},
        redirectcombineentry_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Island::Island(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct IslandDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IslandDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IslandDefaultTypeInternal() {}
  union {
    Island _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IslandDefaultTypeInternal _Island_default_instance_;

inline constexpr Home::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        gamepath_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        launchgame_{nullptr},
        island_{nullptr},
        selectedindex_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Home::Home(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HomeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HomeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HomeDefaultTypeInternal() {}
  union {
    Home _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HomeDefaultTypeInternal _Home_default_instance_;

inline constexpr Settings::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        home_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Settings::Settings(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SettingsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SettingsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SettingsDefaultTypeInternal() {}
  union {
    Settings _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SettingsDefaultTypeInternal _Settings_default_instance_;
}  // namespace Proto
}  // namespace Service
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_settings_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_settings_2eproto = nullptr;
const ::uint32_t
    TableStruct_settings_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Home, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Home, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Home, _impl_.gamepath_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Home, _impl_.launchgame_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Home, _impl_.island_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Home, _impl_.selectedindex_),
        ~0u,
        0,
        1,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Service::Proto::LaunchGame, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Service::Proto::LaunchGame, _impl_.usinghoyolabaccount_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::LaunchGame, _impl_.arecommandlineargumentsenabled_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::LaunchGame, _impl_.iswindowshdrenabled_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::LaunchGame, _impl_.isfullscreen_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::LaunchGame, _impl_.isexclusive_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::LaunchGame, _impl_.isborderless_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::LaunchGame, _impl_.isscreenwidthenabled_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::LaunchGame, _impl_.screenwidth_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::LaunchGame, _impl_.isscreenheightenabled_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::LaunchGame, _impl_.screenheight_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island_ItemsEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island_ItemsEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island_ItemsEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island_ItemsEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.enablesetfieldofview_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.fieldofview_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.fixlowfovscene_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.disablefog_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.enablesettargetframerate_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.targetframerate_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.removeopenteamprogress_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.hidequestbanner_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.disableeventcameramove_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.disableshowdamagetext_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.usingtouchscreen_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.redirectcombineentry_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Island, _impl_.items_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Settings, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Settings, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Service::Proto::Settings, _impl_.home_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::Service::Proto::Home)},
        {16, -1, -1, sizeof(::Service::Proto::LaunchGame)},
        {34, 44, -1, sizeof(::Service::Proto::Island_ItemsEntry_DoNotUse)},
        {46, -1, -1, sizeof(::Service::Proto::Island)},
        {67, 76, -1, sizeof(::Service::Proto::Settings)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Service::Proto::_Home_default_instance_._instance,
    &::Service::Proto::_LaunchGame_default_instance_._instance,
    &::Service::Proto::_Island_ItemsEntry_DoNotUse_default_instance_._instance,
    &::Service::Proto::_Island_default_instance_._instance,
    &::Service::Proto::_Settings_default_instance_._instance,
};
const char descriptor_table_protodef_settings_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016settings.proto\022\rService.Proto\"\205\001\n\004Home"
    "\022\020\n\010GamePath\030\001 \001(\t\022-\n\nLaunchGame\030\002 \001(\0132\031"
    ".Service.Proto.LaunchGame\022%\n\006Island\030\003 \001("
    "\0132\025.Service.Proto.Island\022\025\n\rSelectedInde"
    "x\030\004 \001(\005\"\227\002\n\nLaunchGame\022\033\n\023UsingHoyolabAc"
    "count\030\001 \001(\010\022&\n\036AreCommandLineArgumentsEn"
    "abled\030\002 \001(\010\022\033\n\023IsWindowsHDREnabled\030\003 \001(\010"
    "\022\024\n\014IsFullScreen\030\004 \001(\010\022\023\n\013IsExclusive\030\005 "
    "\001(\010\022\024\n\014IsBorderless\030\006 \001(\010\022\034\n\024IsScreenWid"
    "thEnabled\030\007 \001(\010\022\023\n\013ScreenWidth\030\010 \001(\005\022\035\n\025"
    "IsScreenHeightEnabled\030\t \001(\010\022\024\n\014ScreenHei"
    "ght\030\n \001(\005\"\261\003\n\006Island\022\034\n\024EnableSetFieldOf"
    "View\030\001 \001(\010\022\023\n\013FieldOfView\030\002 \001(\002\022\026\n\016FixLo"
    "wFovScene\030\003 \001(\010\022\022\n\nDisableFog\030\004 \001(\010\022 \n\030E"
    "nableSetTargetFrameRate\030\005 \001(\010\022\027\n\017TargetF"
    "rameRate\030\006 \001(\005\022\036\n\026RemoveOpenTeamProgress"
    "\030\007 \001(\010\022\027\n\017HideQuestBanner\030\010 \001(\010\022\036\n\026Disab"
    "leEventCameraMove\030\t \001(\010\022\035\n\025DisableShowDa"
    "mageText\030\n \001(\010\022\030\n\020UsingTouchScreen\030\013 \001(\010"
    "\022\034\n\024RedirectCombineEntry\030\014 \001(\010\022/\n\005items\030"
    "\r \003(\0132 .Service.Proto.Island.ItemsEntry\032"
    ",\n\nItemsEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001("
    "\010:\0028\001\"-\n\010Settings\022!\n\004Home\030\001 \001(\0132\023.Servic"
    "e.Proto.Homeb\006proto3"
};
static ::absl::once_flag descriptor_table_settings_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_settings_2eproto = {
    false,
    false,
    940,
    descriptor_table_protodef_settings_2eproto,
    "settings.proto",
    &descriptor_table_settings_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_settings_2eproto::offsets,
    file_level_enum_descriptors_settings_2eproto,
    file_level_service_descriptors_settings_2eproto,
};
namespace Service {
namespace Proto {
// ===================================================================

class Home::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Home>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Home, _impl_._has_bits_);
};

Home::Home(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Service.Proto.Home)
}
inline PROTOBUF_NDEBUG_INLINE Home::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Service::Proto::Home& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        gamepath_(arena, from.gamepath_) {}

Home::Home(
    ::google::protobuf::Arena* arena,
    const Home& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Home* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.launchgame_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Service::Proto::LaunchGame>(
                              arena, *from._impl_.launchgame_)
                        : nullptr;
  _impl_.island_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::Service::Proto::Island>(
                              arena, *from._impl_.island_)
                        : nullptr;
  _impl_.selectedindex_ = from._impl_.selectedindex_;

  // @@protoc_insertion_point(copy_constructor:Service.Proto.Home)
}
inline PROTOBUF_NDEBUG_INLINE Home::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        gamepath_(arena) {}

inline void Home::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, launchgame_),
           0,
           offsetof(Impl_, selectedindex_) -
               offsetof(Impl_, launchgame_) +
               sizeof(Impl_::selectedindex_));
}
Home::~Home() {
  // @@protoc_insertion_point(destructor:Service.Proto.Home)
  SharedDtor(*this);
}
inline void Home::SharedDtor(MessageLite& self) {
  Home& this_ = static_cast<Home&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.gamepath_.Destroy();
  delete this_._impl_.launchgame_;
  delete this_._impl_.island_;
  this_._impl_.~Impl_();
}

inline void* Home::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Home(arena);
}
constexpr auto Home::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Home),
                                            alignof(Home));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Home::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Home_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Home::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Home>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Home::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Home>(), &Home::ByteSizeLong,
            &Home::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Home, _impl_._cached_size_),
        false,
    },
    &Home::kDescriptorMethods,
    &descriptor_table_settings_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Home::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 2, 35, 2> Home::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Home, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Service::Proto::Home>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 SelectedIndex = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Home, _impl_.selectedindex_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Home, _impl_.selectedindex_)}},
    // string GamePath = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Home, _impl_.gamepath_)}},
    // .Service.Proto.LaunchGame LaunchGame = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Home, _impl_.launchgame_)}},
    // .Service.Proto.Island Island = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(Home, _impl_.island_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string GamePath = 1;
    {PROTOBUF_FIELD_OFFSET(Home, _impl_.gamepath_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .Service.Proto.LaunchGame LaunchGame = 2;
    {PROTOBUF_FIELD_OFFSET(Home, _impl_.launchgame_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Service.Proto.Island Island = 3;
    {PROTOBUF_FIELD_OFFSET(Home, _impl_.island_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // int32 SelectedIndex = 4;
    {PROTOBUF_FIELD_OFFSET(Home, _impl_.selectedindex_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Service::Proto::LaunchGame>()},
    {::_pbi::TcParser::GetTable<::Service::Proto::Island>()},
  }}, {{
    "\22\10\0\0\0\0\0\0"
    "Service.Proto.Home"
    "GamePath"
  }},
};

PROTOBUF_NOINLINE void Home::Clear() {
// @@protoc_insertion_point(message_clear_start:Service.Proto.Home)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.gamepath_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.launchgame_ != nullptr);
      _impl_.launchgame_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.island_ != nullptr);
      _impl_.island_->Clear();
    }
  }
  _impl_.selectedindex_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Home::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Home& this_ = static_cast<const Home&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Home::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Home& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Service.Proto.Home)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string GamePath = 1;
          if (!this_._internal_gamepath().empty()) {
            const std::string& _s = this_._internal_gamepath();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Service.Proto.Home.GamePath");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Service.Proto.LaunchGame LaunchGame = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.launchgame_, this_._impl_.launchgame_->GetCachedSize(), target,
                stream);
          }

          // .Service.Proto.Island Island = 3;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.island_, this_._impl_.island_->GetCachedSize(), target,
                stream);
          }

          // int32 SelectedIndex = 4;
          if (this_._internal_selectedindex() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_selectedindex(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Service.Proto.Home)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Home::ByteSizeLong(const MessageLite& base) {
          const Home& this_ = static_cast<const Home&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Home::ByteSizeLong() const {
          const Home& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Service.Proto.Home)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string GamePath = 1;
            if (!this_._internal_gamepath().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_gamepath());
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .Service.Proto.LaunchGame LaunchGame = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.launchgame_);
            }
            // .Service.Proto.Island Island = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.island_);
            }
          }
           {
            // int32 SelectedIndex = 4;
            if (this_._internal_selectedindex() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_selectedindex());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Home::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Home*>(&to_msg);
  auto& from = static_cast<const Home&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Service.Proto.Home)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_gamepath().empty()) {
    _this->_internal_set_gamepath(from._internal_gamepath());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.launchgame_ != nullptr);
      if (_this->_impl_.launchgame_ == nullptr) {
        _this->_impl_.launchgame_ =
            ::google::protobuf::Message::CopyConstruct<::Service::Proto::LaunchGame>(arena, *from._impl_.launchgame_);
      } else {
        _this->_impl_.launchgame_->MergeFrom(*from._impl_.launchgame_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.island_ != nullptr);
      if (_this->_impl_.island_ == nullptr) {
        _this->_impl_.island_ =
            ::google::protobuf::Message::CopyConstruct<::Service::Proto::Island>(arena, *from._impl_.island_);
      } else {
        _this->_impl_.island_->MergeFrom(*from._impl_.island_);
      }
    }
  }
  if (from._internal_selectedindex() != 0) {
    _this->_impl_.selectedindex_ = from._impl_.selectedindex_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Home::CopyFrom(const Home& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Service.Proto.Home)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Home::InternalSwap(Home* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.gamepath_, &other->_impl_.gamepath_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Home, _impl_.selectedindex_)
      + sizeof(Home::_impl_.selectedindex_)
      - PROTOBUF_FIELD_OFFSET(Home, _impl_.launchgame_)>(
          reinterpret_cast<char*>(&_impl_.launchgame_),
          reinterpret_cast<char*>(&other->_impl_.launchgame_));
}

::google::protobuf::Metadata Home::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LaunchGame::_Internal {
 public:
};

LaunchGame::LaunchGame(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Service.Proto.LaunchGame)
}
LaunchGame::LaunchGame(
    ::google::protobuf::Arena* arena, const LaunchGame& from)
    : LaunchGame(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE LaunchGame::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LaunchGame::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, usinghoyolabaccount_),
           0,
           offsetof(Impl_, screenheight_) -
               offsetof(Impl_, usinghoyolabaccount_) +
               sizeof(Impl_::screenheight_));
}
LaunchGame::~LaunchGame() {
  // @@protoc_insertion_point(destructor:Service.Proto.LaunchGame)
  SharedDtor(*this);
}
inline void LaunchGame::SharedDtor(MessageLite& self) {
  LaunchGame& this_ = static_cast<LaunchGame&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* LaunchGame::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) LaunchGame(arena);
}
constexpr auto LaunchGame::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(LaunchGame),
                                            alignof(LaunchGame));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull LaunchGame::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_LaunchGame_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &LaunchGame::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<LaunchGame>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &LaunchGame::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<LaunchGame>(), &LaunchGame::ByteSizeLong,
            &LaunchGame::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_._cached_size_),
        false,
    },
    &LaunchGame::kDescriptorMethods,
    &descriptor_table_settings_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* LaunchGame::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 10, 0, 0, 2> LaunchGame::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    10, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Service::Proto::LaunchGame>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool UsingHoyolabAccount = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LaunchGame, _impl_.usinghoyolabaccount_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.usinghoyolabaccount_)}},
    // bool AreCommandLineArgumentsEnabled = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LaunchGame, _impl_.arecommandlineargumentsenabled_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.arecommandlineargumentsenabled_)}},
    // bool IsWindowsHDREnabled = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LaunchGame, _impl_.iswindowshdrenabled_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.iswindowshdrenabled_)}},
    // bool IsFullScreen = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LaunchGame, _impl_.isfullscreen_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.isfullscreen_)}},
    // bool IsExclusive = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LaunchGame, _impl_.isexclusive_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.isexclusive_)}},
    // bool IsBorderless = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LaunchGame, _impl_.isborderless_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.isborderless_)}},
    // bool IsScreenWidthEnabled = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LaunchGame, _impl_.isscreenwidthenabled_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.isscreenwidthenabled_)}},
    // int32 ScreenWidth = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LaunchGame, _impl_.screenwidth_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.screenwidth_)}},
    // bool IsScreenHeightEnabled = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LaunchGame, _impl_.isscreenheightenabled_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.isscreenheightenabled_)}},
    // int32 ScreenHeight = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LaunchGame, _impl_.screenheight_), 63>(),
     {80, 63, 0, PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.screenheight_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // bool UsingHoyolabAccount = 1;
    {PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.usinghoyolabaccount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool AreCommandLineArgumentsEnabled = 2;
    {PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.arecommandlineargumentsenabled_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool IsWindowsHDREnabled = 3;
    {PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.iswindowshdrenabled_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool IsFullScreen = 4;
    {PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.isfullscreen_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool IsExclusive = 5;
    {PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.isexclusive_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool IsBorderless = 6;
    {PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.isborderless_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool IsScreenWidthEnabled = 7;
    {PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.isscreenwidthenabled_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int32 ScreenWidth = 8;
    {PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.screenwidth_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool IsScreenHeightEnabled = 9;
    {PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.isscreenheightenabled_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int32 ScreenHeight = 10;
    {PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.screenheight_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void LaunchGame::Clear() {
// @@protoc_insertion_point(message_clear_start:Service.Proto.LaunchGame)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.usinghoyolabaccount_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.screenheight_) -
      reinterpret_cast<char*>(&_impl_.usinghoyolabaccount_)) + sizeof(_impl_.screenheight_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LaunchGame::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LaunchGame& this_ = static_cast<const LaunchGame&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LaunchGame::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LaunchGame& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Service.Proto.LaunchGame)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool UsingHoyolabAccount = 1;
          if (this_._internal_usinghoyolabaccount() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_usinghoyolabaccount(), target);
          }

          // bool AreCommandLineArgumentsEnabled = 2;
          if (this_._internal_arecommandlineargumentsenabled() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_arecommandlineargumentsenabled(), target);
          }

          // bool IsWindowsHDREnabled = 3;
          if (this_._internal_iswindowshdrenabled() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_iswindowshdrenabled(), target);
          }

          // bool IsFullScreen = 4;
          if (this_._internal_isfullscreen() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_isfullscreen(), target);
          }

          // bool IsExclusive = 5;
          if (this_._internal_isexclusive() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_isexclusive(), target);
          }

          // bool IsBorderless = 6;
          if (this_._internal_isborderless() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                6, this_._internal_isborderless(), target);
          }

          // bool IsScreenWidthEnabled = 7;
          if (this_._internal_isscreenwidthenabled() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                7, this_._internal_isscreenwidthenabled(), target);
          }

          // int32 ScreenWidth = 8;
          if (this_._internal_screenwidth() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<8>(
                    stream, this_._internal_screenwidth(), target);
          }

          // bool IsScreenHeightEnabled = 9;
          if (this_._internal_isscreenheightenabled() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                9, this_._internal_isscreenheightenabled(), target);
          }

          // int32 ScreenHeight = 10;
          if (this_._internal_screenheight() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<10>(
                    stream, this_._internal_screenheight(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Service.Proto.LaunchGame)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LaunchGame::ByteSizeLong(const MessageLite& base) {
          const LaunchGame& this_ = static_cast<const LaunchGame&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LaunchGame::ByteSizeLong() const {
          const LaunchGame& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Service.Proto.LaunchGame)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bool UsingHoyolabAccount = 1;
            if (this_._internal_usinghoyolabaccount() != 0) {
              total_size += 2;
            }
            // bool AreCommandLineArgumentsEnabled = 2;
            if (this_._internal_arecommandlineargumentsenabled() != 0) {
              total_size += 2;
            }
            // bool IsWindowsHDREnabled = 3;
            if (this_._internal_iswindowshdrenabled() != 0) {
              total_size += 2;
            }
            // bool IsFullScreen = 4;
            if (this_._internal_isfullscreen() != 0) {
              total_size += 2;
            }
            // bool IsExclusive = 5;
            if (this_._internal_isexclusive() != 0) {
              total_size += 2;
            }
            // bool IsBorderless = 6;
            if (this_._internal_isborderless() != 0) {
              total_size += 2;
            }
            // bool IsScreenWidthEnabled = 7;
            if (this_._internal_isscreenwidthenabled() != 0) {
              total_size += 2;
            }
            // bool IsScreenHeightEnabled = 9;
            if (this_._internal_isscreenheightenabled() != 0) {
              total_size += 2;
            }
            // int32 ScreenWidth = 8;
            if (this_._internal_screenwidth() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_screenwidth());
            }
            // int32 ScreenHeight = 10;
            if (this_._internal_screenheight() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_screenheight());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LaunchGame::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LaunchGame*>(&to_msg);
  auto& from = static_cast<const LaunchGame&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Service.Proto.LaunchGame)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_usinghoyolabaccount() != 0) {
    _this->_impl_.usinghoyolabaccount_ = from._impl_.usinghoyolabaccount_;
  }
  if (from._internal_arecommandlineargumentsenabled() != 0) {
    _this->_impl_.arecommandlineargumentsenabled_ = from._impl_.arecommandlineargumentsenabled_;
  }
  if (from._internal_iswindowshdrenabled() != 0) {
    _this->_impl_.iswindowshdrenabled_ = from._impl_.iswindowshdrenabled_;
  }
  if (from._internal_isfullscreen() != 0) {
    _this->_impl_.isfullscreen_ = from._impl_.isfullscreen_;
  }
  if (from._internal_isexclusive() != 0) {
    _this->_impl_.isexclusive_ = from._impl_.isexclusive_;
  }
  if (from._internal_isborderless() != 0) {
    _this->_impl_.isborderless_ = from._impl_.isborderless_;
  }
  if (from._internal_isscreenwidthenabled() != 0) {
    _this->_impl_.isscreenwidthenabled_ = from._impl_.isscreenwidthenabled_;
  }
  if (from._internal_isscreenheightenabled() != 0) {
    _this->_impl_.isscreenheightenabled_ = from._impl_.isscreenheightenabled_;
  }
  if (from._internal_screenwidth() != 0) {
    _this->_impl_.screenwidth_ = from._impl_.screenwidth_;
  }
  if (from._internal_screenheight() != 0) {
    _this->_impl_.screenheight_ = from._impl_.screenheight_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LaunchGame::CopyFrom(const LaunchGame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Service.Proto.LaunchGame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LaunchGame::InternalSwap(LaunchGame* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.screenheight_)
      + sizeof(LaunchGame::_impl_.screenheight_)
      - PROTOBUF_FIELD_OFFSET(LaunchGame, _impl_.usinghoyolabaccount_)>(
          reinterpret_cast<char*>(&_impl_.usinghoyolabaccount_),
          reinterpret_cast<char*>(&other->_impl_.usinghoyolabaccount_));
}

::google::protobuf::Metadata LaunchGame::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              Island_ItemsEntry_DoNotUse::Island_ItemsEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              Island_ItemsEntry_DoNotUse::Island_ItemsEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              Island_ItemsEntry_DoNotUse::Island_ItemsEntry_DoNotUse() : SuperType() {}
              Island_ItemsEntry_DoNotUse::Island_ItemsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* Island_ItemsEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) Island_ItemsEntry_DoNotUse(arena);
              }
              constexpr auto Island_ItemsEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Island_ItemsEntry_DoNotUse),
                                                          alignof(Island_ItemsEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull Island_ItemsEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_Island_ItemsEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &Island_ItemsEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<Island_ItemsEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &Island_ItemsEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &Island_ItemsEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(Island_ItemsEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &Island_ItemsEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_settings_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* Island_ItemsEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Island_ItemsEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Island_ItemsEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Service::Proto::Island_ItemsEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Island_ItemsEntry_DoNotUse, _impl_.value_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Island_ItemsEntry_DoNotUse, _impl_.value_)}},
    // int32 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Island_ItemsEntry_DoNotUse, _impl_.key_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Island_ItemsEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 key = 1;
    {PROTOBUF_FIELD_OFFSET(Island_ItemsEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool value = 2;
    {PROTOBUF_FIELD_OFFSET(Island_ItemsEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

// ===================================================================

class Island::_Internal {
 public:
};

Island::Island(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Service.Proto.Island)
}
inline PROTOBUF_NDEBUG_INLINE Island::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Service::Proto::Island& from_msg)
      : items_{visibility, arena, from.items_},
        _cached_size_{0} {}

Island::Island(
    ::google::protobuf::Arena* arena,
    const Island& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Island* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, fieldofview_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, fieldofview_),
           offsetof(Impl_, redirectcombineentry_) -
               offsetof(Impl_, fieldofview_) +
               sizeof(Impl_::redirectcombineentry_));

  // @@protoc_insertion_point(copy_constructor:Service.Proto.Island)
}
inline PROTOBUF_NDEBUG_INLINE Island::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : items_{visibility, arena},
        _cached_size_{0} {}

inline void Island::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, fieldofview_),
           0,
           offsetof(Impl_, redirectcombineentry_) -
               offsetof(Impl_, fieldofview_) +
               sizeof(Impl_::redirectcombineentry_));
}
Island::~Island() {
  // @@protoc_insertion_point(destructor:Service.Proto.Island)
  SharedDtor(*this);
}
inline void Island::SharedDtor(MessageLite& self) {
  Island& this_ = static_cast<Island&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Island::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Island(arena);
}
constexpr auto Island::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Island, _impl_.items_) +
          decltype(Island::_impl_.items_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Island, _impl_.items_) +
          decltype(Island::_impl_.items_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Island), alignof(Island), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Island::PlacementNew_,
                                 sizeof(Island),
                                 alignof(Island));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Island::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Island_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Island::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Island>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Island::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Island>(), &Island::ByteSizeLong,
            &Island::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Island, _impl_._cached_size_),
        false,
    },
    &Island::kDescriptorMethods,
    &descriptor_table_settings_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Island::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 13, 1, 0, 2> Island::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    13, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294959104,  // skipmap
    offsetof(decltype(_table_), field_entries),
    13,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Service::Proto::Island>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool EnableSetFieldOfView = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Island, _impl_.enablesetfieldofview_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.enablesetfieldofview_)}},
    // float FieldOfView = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.fieldofview_)}},
    // bool FixLowFovScene = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Island, _impl_.fixlowfovscene_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.fixlowfovscene_)}},
    // bool DisableFog = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Island, _impl_.disablefog_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.disablefog_)}},
    // bool EnableSetTargetFrameRate = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Island, _impl_.enablesettargetframerate_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.enablesettargetframerate_)}},
    // int32 TargetFrameRate = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Island, _impl_.targetframerate_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.targetframerate_)}},
    // bool RemoveOpenTeamProgress = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Island, _impl_.removeopenteamprogress_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.removeopenteamprogress_)}},
    // bool HideQuestBanner = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Island, _impl_.hidequestbanner_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.hidequestbanner_)}},
    // bool DisableEventCameraMove = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Island, _impl_.disableeventcameramove_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.disableeventcameramove_)}},
    // bool DisableShowDamageText = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Island, _impl_.disableshowdamagetext_), 63>(),
     {80, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.disableshowdamagetext_)}},
    // bool UsingTouchScreen = 11;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Island, _impl_.usingtouchscreen_), 63>(),
     {88, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.usingtouchscreen_)}},
    // bool RedirectCombineEntry = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Island, _impl_.redirectcombineentry_), 63>(),
     {96, 63, 0, PROTOBUF_FIELD_OFFSET(Island, _impl_.redirectcombineentry_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // bool EnableSetFieldOfView = 1;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.enablesetfieldofview_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // float FieldOfView = 2;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.fieldofview_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // bool FixLowFovScene = 3;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.fixlowfovscene_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool DisableFog = 4;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.disablefog_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool EnableSetTargetFrameRate = 5;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.enablesettargetframerate_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int32 TargetFrameRate = 6;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.targetframerate_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool RemoveOpenTeamProgress = 7;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.removeopenteamprogress_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool HideQuestBanner = 8;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.hidequestbanner_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool DisableEventCameraMove = 9;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.disableeventcameramove_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool DisableShowDamageText = 10;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.disableshowdamagetext_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool UsingTouchScreen = 11;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.usingtouchscreen_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool RedirectCombineEntry = 12;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.redirectcombineentry_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // map<int32, bool> items = 13;
    {PROTOBUF_FIELD_OFFSET(Island, _impl_.items_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(Island()._impl_.items_)>(
        0, 0, 0, 5,
        8)},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Island::Clear() {
// @@protoc_insertion_point(message_clear_start:Service.Proto.Island)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.items_.Clear();
  ::memset(&_impl_.fieldofview_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.redirectcombineentry_) -
      reinterpret_cast<char*>(&_impl_.fieldofview_)) + sizeof(_impl_.redirectcombineentry_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Island::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Island& this_ = static_cast<const Island&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Island::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Island& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Service.Proto.Island)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool EnableSetFieldOfView = 1;
          if (this_._internal_enablesetfieldofview() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_enablesetfieldofview(), target);
          }

          // float FieldOfView = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_fieldofview()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_fieldofview(), target);
          }

          // bool FixLowFovScene = 3;
          if (this_._internal_fixlowfovscene() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_fixlowfovscene(), target);
          }

          // bool DisableFog = 4;
          if (this_._internal_disablefog() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_disablefog(), target);
          }

          // bool EnableSetTargetFrameRate = 5;
          if (this_._internal_enablesettargetframerate() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                5, this_._internal_enablesettargetframerate(), target);
          }

          // int32 TargetFrameRate = 6;
          if (this_._internal_targetframerate() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<6>(
                    stream, this_._internal_targetframerate(), target);
          }

          // bool RemoveOpenTeamProgress = 7;
          if (this_._internal_removeopenteamprogress() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                7, this_._internal_removeopenteamprogress(), target);
          }

          // bool HideQuestBanner = 8;
          if (this_._internal_hidequestbanner() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                8, this_._internal_hidequestbanner(), target);
          }

          // bool DisableEventCameraMove = 9;
          if (this_._internal_disableeventcameramove() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                9, this_._internal_disableeventcameramove(), target);
          }

          // bool DisableShowDamageText = 10;
          if (this_._internal_disableshowdamagetext() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                10, this_._internal_disableshowdamagetext(), target);
          }

          // bool UsingTouchScreen = 11;
          if (this_._internal_usingtouchscreen() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                11, this_._internal_usingtouchscreen(), target);
          }

          // bool RedirectCombineEntry = 12;
          if (this_._internal_redirectcombineentry() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                12, this_._internal_redirectcombineentry(), target);
          }

          // map<int32, bool> items = 13;
          if (!this_._internal_items().empty()) {
            using MapType = ::google::protobuf::Map<::int32_t, bool>;
            using WireHelper = _pbi::MapEntryFuncs<::int32_t, bool,
                                           _pbi::WireFormatLite::TYPE_INT32,
                                           _pbi::WireFormatLite::TYPE_BOOL>;
            const auto& field = this_._internal_items();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    13, entry.first, entry.second, target, stream);
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    13, entry.first, entry.second, target, stream);
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Service.Proto.Island)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Island::ByteSizeLong(const MessageLite& base) {
          const Island& this_ = static_cast<const Island&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Island::ByteSizeLong() const {
          const Island& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Service.Proto.Island)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<int32, bool> items = 13;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_items_size());
              for (const auto& entry : this_._internal_items()) {
                total_size += _pbi::MapEntryFuncs<::int32_t, bool,
                                               _pbi::WireFormatLite::TYPE_INT32,
                                               _pbi::WireFormatLite::TYPE_BOOL>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // float FieldOfView = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_fieldofview()) != 0) {
              total_size += 5;
            }
            // bool EnableSetFieldOfView = 1;
            if (this_._internal_enablesetfieldofview() != 0) {
              total_size += 2;
            }
            // bool FixLowFovScene = 3;
            if (this_._internal_fixlowfovscene() != 0) {
              total_size += 2;
            }
            // bool DisableFog = 4;
            if (this_._internal_disablefog() != 0) {
              total_size += 2;
            }
            // bool EnableSetTargetFrameRate = 5;
            if (this_._internal_enablesettargetframerate() != 0) {
              total_size += 2;
            }
            // int32 TargetFrameRate = 6;
            if (this_._internal_targetframerate() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_targetframerate());
            }
            // bool RemoveOpenTeamProgress = 7;
            if (this_._internal_removeopenteamprogress() != 0) {
              total_size += 2;
            }
            // bool HideQuestBanner = 8;
            if (this_._internal_hidequestbanner() != 0) {
              total_size += 2;
            }
            // bool DisableEventCameraMove = 9;
            if (this_._internal_disableeventcameramove() != 0) {
              total_size += 2;
            }
            // bool DisableShowDamageText = 10;
            if (this_._internal_disableshowdamagetext() != 0) {
              total_size += 2;
            }
            // bool UsingTouchScreen = 11;
            if (this_._internal_usingtouchscreen() != 0) {
              total_size += 2;
            }
            // bool RedirectCombineEntry = 12;
            if (this_._internal_redirectcombineentry() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Island::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Island*>(&to_msg);
  auto& from = static_cast<const Island&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Service.Proto.Island)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.items_.MergeFrom(from._impl_.items_);
  if (::absl::bit_cast<::uint32_t>(from._internal_fieldofview()) != 0) {
    _this->_impl_.fieldofview_ = from._impl_.fieldofview_;
  }
  if (from._internal_enablesetfieldofview() != 0) {
    _this->_impl_.enablesetfieldofview_ = from._impl_.enablesetfieldofview_;
  }
  if (from._internal_fixlowfovscene() != 0) {
    _this->_impl_.fixlowfovscene_ = from._impl_.fixlowfovscene_;
  }
  if (from._internal_disablefog() != 0) {
    _this->_impl_.disablefog_ = from._impl_.disablefog_;
  }
  if (from._internal_enablesettargetframerate() != 0) {
    _this->_impl_.enablesettargetframerate_ = from._impl_.enablesettargetframerate_;
  }
  if (from._internal_targetframerate() != 0) {
    _this->_impl_.targetframerate_ = from._impl_.targetframerate_;
  }
  if (from._internal_removeopenteamprogress() != 0) {
    _this->_impl_.removeopenteamprogress_ = from._impl_.removeopenteamprogress_;
  }
  if (from._internal_hidequestbanner() != 0) {
    _this->_impl_.hidequestbanner_ = from._impl_.hidequestbanner_;
  }
  if (from._internal_disableeventcameramove() != 0) {
    _this->_impl_.disableeventcameramove_ = from._impl_.disableeventcameramove_;
  }
  if (from._internal_disableshowdamagetext() != 0) {
    _this->_impl_.disableshowdamagetext_ = from._impl_.disableshowdamagetext_;
  }
  if (from._internal_usingtouchscreen() != 0) {
    _this->_impl_.usingtouchscreen_ = from._impl_.usingtouchscreen_;
  }
  if (from._internal_redirectcombineentry() != 0) {
    _this->_impl_.redirectcombineentry_ = from._impl_.redirectcombineentry_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Island::CopyFrom(const Island& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Service.Proto.Island)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Island::InternalSwap(Island* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Island, _impl_.redirectcombineentry_)
      + sizeof(Island::_impl_.redirectcombineentry_)
      - PROTOBUF_FIELD_OFFSET(Island, _impl_.fieldofview_)>(
          reinterpret_cast<char*>(&_impl_.fieldofview_),
          reinterpret_cast<char*>(&other->_impl_.fieldofview_));
}

::google::protobuf::Metadata Island::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Settings::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Settings>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Settings, _impl_._has_bits_);
};

Settings::Settings(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Service.Proto.Settings)
}
inline PROTOBUF_NDEBUG_INLINE Settings::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Service::Proto::Settings& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Settings::Settings(
    ::google::protobuf::Arena* arena,
    const Settings& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Settings* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.home_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Service::Proto::Home>(
                              arena, *from._impl_.home_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:Service.Proto.Settings)
}
inline PROTOBUF_NDEBUG_INLINE Settings::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Settings::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.home_ = {};
}
Settings::~Settings() {
  // @@protoc_insertion_point(destructor:Service.Proto.Settings)
  SharedDtor(*this);
}
inline void Settings::SharedDtor(MessageLite& self) {
  Settings& this_ = static_cast<Settings&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.home_;
  this_._impl_.~Impl_();
}

inline void* Settings::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Settings(arena);
}
constexpr auto Settings::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Settings),
                                            alignof(Settings));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Settings::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Settings_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Settings::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Settings>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Settings::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Settings>(), &Settings::ByteSizeLong,
            &Settings::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Settings, _impl_._cached_size_),
        false,
    },
    &Settings::kDescriptorMethods,
    &descriptor_table_settings_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Settings::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> Settings::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Settings, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Service::Proto::Settings>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Service.Proto.Home Home = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Settings, _impl_.home_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Service.Proto.Home Home = 1;
    {PROTOBUF_FIELD_OFFSET(Settings, _impl_.home_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Service::Proto::Home>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Settings::Clear() {
// @@protoc_insertion_point(message_clear_start:Service.Proto.Settings)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.home_ != nullptr);
    _impl_.home_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Settings::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Settings& this_ = static_cast<const Settings&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Settings::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Settings& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Service.Proto.Settings)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Service.Proto.Home Home = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.home_, this_._impl_.home_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Service.Proto.Settings)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Settings::ByteSizeLong(const MessageLite& base) {
          const Settings& this_ = static_cast<const Settings&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Settings::ByteSizeLong() const {
          const Settings& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Service.Proto.Settings)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .Service.Proto.Home Home = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.home_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Settings::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Settings*>(&to_msg);
  auto& from = static_cast<const Settings&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Service.Proto.Settings)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.home_ != nullptr);
    if (_this->_impl_.home_ == nullptr) {
      _this->_impl_.home_ =
          ::google::protobuf::Message::CopyConstruct<::Service::Proto::Home>(arena, *from._impl_.home_);
    } else {
      _this->_impl_.home_->MergeFrom(*from._impl_.home_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Settings::CopyFrom(const Settings& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Service.Proto.Settings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Settings::InternalSwap(Settings* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.home_, other->_impl_.home_);
}

::google::protobuf::Metadata Settings::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
}  // namespace Service
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_settings_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
