// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: settings.proto
// Protobuf C++ Version: 5.29.5

#ifndef settings_2eproto_2epb_2eh
#define settings_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_settings_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_settings_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_settings_2eproto;
namespace Service {
namespace Proto {
class Home;
struct HomeDefaultTypeInternal;
extern HomeDefaultTypeInternal _Home_default_instance_;
class Island;
struct IslandDefaultTypeInternal;
extern IslandDefaultTypeInternal _Island_default_instance_;
class Island_ItemsEntry_DoNotUse;
struct Island_ItemsEntry_DoNotUseDefaultTypeInternal;
extern Island_ItemsEntry_DoNotUseDefaultTypeInternal _Island_ItemsEntry_DoNotUse_default_instance_;
class LaunchGame;
struct LaunchGameDefaultTypeInternal;
extern LaunchGameDefaultTypeInternal _LaunchGame_default_instance_;
class Settings;
struct SettingsDefaultTypeInternal;
extern SettingsDefaultTypeInternal _Settings_default_instance_;
}  // namespace Proto
}  // namespace Service
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Service {
namespace Proto {

// ===================================================================


// -------------------------------------------------------------------

class LaunchGame final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Service.Proto.LaunchGame) */ {
 public:
  inline LaunchGame() : LaunchGame(nullptr) {}
  ~LaunchGame() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LaunchGame* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LaunchGame));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LaunchGame(
      ::google::protobuf::internal::ConstantInitialized);

  inline LaunchGame(const LaunchGame& from) : LaunchGame(nullptr, from) {}
  inline LaunchGame(LaunchGame&& from) noexcept
      : LaunchGame(nullptr, std::move(from)) {}
  inline LaunchGame& operator=(const LaunchGame& from) {
    CopyFrom(from);
    return *this;
  }
  inline LaunchGame& operator=(LaunchGame&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LaunchGame& default_instance() {
    return *internal_default_instance();
  }
  static inline const LaunchGame* internal_default_instance() {
    return reinterpret_cast<const LaunchGame*>(
        &_LaunchGame_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(LaunchGame& a, LaunchGame& b) { a.Swap(&b); }
  inline void Swap(LaunchGame* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LaunchGame* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LaunchGame* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LaunchGame>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LaunchGame& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LaunchGame& from) { LaunchGame::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LaunchGame* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Service.Proto.LaunchGame"; }

 protected:
  explicit LaunchGame(::google::protobuf::Arena* arena);
  LaunchGame(::google::protobuf::Arena* arena, const LaunchGame& from);
  LaunchGame(::google::protobuf::Arena* arena, LaunchGame&& from) noexcept
      : LaunchGame(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUsingHoyolabAccountFieldNumber = 1,
    kAreCommandLineArgumentsEnabledFieldNumber = 2,
    kIsWindowsHDREnabledFieldNumber = 3,
    kIsFullScreenFieldNumber = 4,
    kIsExclusiveFieldNumber = 5,
    kIsBorderlessFieldNumber = 6,
    kIsScreenWidthEnabledFieldNumber = 7,
    kIsScreenHeightEnabledFieldNumber = 9,
    kScreenWidthFieldNumber = 8,
    kScreenHeightFieldNumber = 10,
  };
  // bool UsingHoyolabAccount = 1;
  void clear_usinghoyolabaccount() ;
  bool usinghoyolabaccount() const;
  void set_usinghoyolabaccount(bool value);

  private:
  bool _internal_usinghoyolabaccount() const;
  void _internal_set_usinghoyolabaccount(bool value);

  public:
  // bool AreCommandLineArgumentsEnabled = 2;
  void clear_arecommandlineargumentsenabled() ;
  bool arecommandlineargumentsenabled() const;
  void set_arecommandlineargumentsenabled(bool value);

  private:
  bool _internal_arecommandlineargumentsenabled() const;
  void _internal_set_arecommandlineargumentsenabled(bool value);

  public:
  // bool IsWindowsHDREnabled = 3;
  void clear_iswindowshdrenabled() ;
  bool iswindowshdrenabled() const;
  void set_iswindowshdrenabled(bool value);

  private:
  bool _internal_iswindowshdrenabled() const;
  void _internal_set_iswindowshdrenabled(bool value);

  public:
  // bool IsFullScreen = 4;
  void clear_isfullscreen() ;
  bool isfullscreen() const;
  void set_isfullscreen(bool value);

  private:
  bool _internal_isfullscreen() const;
  void _internal_set_isfullscreen(bool value);

  public:
  // bool IsExclusive = 5;
  void clear_isexclusive() ;
  bool isexclusive() const;
  void set_isexclusive(bool value);

  private:
  bool _internal_isexclusive() const;
  void _internal_set_isexclusive(bool value);

  public:
  // bool IsBorderless = 6;
  void clear_isborderless() ;
  bool isborderless() const;
  void set_isborderless(bool value);

  private:
  bool _internal_isborderless() const;
  void _internal_set_isborderless(bool value);

  public:
  // bool IsScreenWidthEnabled = 7;
  void clear_isscreenwidthenabled() ;
  bool isscreenwidthenabled() const;
  void set_isscreenwidthenabled(bool value);

  private:
  bool _internal_isscreenwidthenabled() const;
  void _internal_set_isscreenwidthenabled(bool value);

  public:
  // bool IsScreenHeightEnabled = 9;
  void clear_isscreenheightenabled() ;
  bool isscreenheightenabled() const;
  void set_isscreenheightenabled(bool value);

  private:
  bool _internal_isscreenheightenabled() const;
  void _internal_set_isscreenheightenabled(bool value);

  public:
  // int32 ScreenWidth = 8;
  void clear_screenwidth() ;
  ::int32_t screenwidth() const;
  void set_screenwidth(::int32_t value);

  private:
  ::int32_t _internal_screenwidth() const;
  void _internal_set_screenwidth(::int32_t value);

  public:
  // int32 ScreenHeight = 10;
  void clear_screenheight() ;
  ::int32_t screenheight() const;
  void set_screenheight(::int32_t value);

  private:
  ::int32_t _internal_screenheight() const;
  void _internal_set_screenheight(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Service.Proto.LaunchGame)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 10, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LaunchGame& from_msg);
    bool usinghoyolabaccount_;
    bool arecommandlineargumentsenabled_;
    bool iswindowshdrenabled_;
    bool isfullscreen_;
    bool isexclusive_;
    bool isborderless_;
    bool isscreenwidthenabled_;
    bool isscreenheightenabled_;
    ::int32_t screenwidth_;
    ::int32_t screenheight_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_settings_2eproto;
};
// -------------------------------------------------------------------

class Island_ItemsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          ::int32_t, bool,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
          ::google::protobuf::internal::WireFormatLite::TYPE_BOOL> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      ::int32_t, bool,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>;
  Island_ItemsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Island_ItemsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit Island_ItemsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const Island_ItemsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const Island_ItemsEntry_DoNotUse*>(
        &_Island_ItemsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_settings_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class Island final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Service.Proto.Island) */ {
 public:
  inline Island() : Island(nullptr) {}
  ~Island() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Island* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Island));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Island(
      ::google::protobuf::internal::ConstantInitialized);

  inline Island(const Island& from) : Island(nullptr, from) {}
  inline Island(Island&& from) noexcept
      : Island(nullptr, std::move(from)) {}
  inline Island& operator=(const Island& from) {
    CopyFrom(from);
    return *this;
  }
  inline Island& operator=(Island&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Island& default_instance() {
    return *internal_default_instance();
  }
  static inline const Island* internal_default_instance() {
    return reinterpret_cast<const Island*>(
        &_Island_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Island& a, Island& b) { a.Swap(&b); }
  inline void Swap(Island* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Island* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Island* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Island>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Island& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Island& from) { Island::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Island* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Service.Proto.Island"; }

 protected:
  explicit Island(::google::protobuf::Arena* arena);
  Island(::google::protobuf::Arena* arena, const Island& from);
  Island(::google::protobuf::Arena* arena, Island&& from) noexcept
      : Island(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kItemsFieldNumber = 13,
    kFieldOfViewFieldNumber = 2,
    kEnableSetFieldOfViewFieldNumber = 1,
    kFixLowFovSceneFieldNumber = 3,
    kDisableFogFieldNumber = 4,
    kEnableSetTargetFrameRateFieldNumber = 5,
    kTargetFrameRateFieldNumber = 6,
    kRemoveOpenTeamProgressFieldNumber = 7,
    kHideQuestBannerFieldNumber = 8,
    kDisableEventCameraMoveFieldNumber = 9,
    kDisableShowDamageTextFieldNumber = 10,
    kUsingTouchScreenFieldNumber = 11,
    kRedirectCombineEntryFieldNumber = 12,
  };
  // map<int32, bool> items = 13;
  int items_size() const;
  private:
  int _internal_items_size() const;

  public:
  void clear_items() ;
  const ::google::protobuf::Map<::int32_t, bool>& items() const;
  ::google::protobuf::Map<::int32_t, bool>* mutable_items();

  private:
  const ::google::protobuf::Map<::int32_t, bool>& _internal_items() const;
  ::google::protobuf::Map<::int32_t, bool>* _internal_mutable_items();

  public:
  // float FieldOfView = 2;
  void clear_fieldofview() ;
  float fieldofview() const;
  void set_fieldofview(float value);

  private:
  float _internal_fieldofview() const;
  void _internal_set_fieldofview(float value);

  public:
  // bool EnableSetFieldOfView = 1;
  void clear_enablesetfieldofview() ;
  bool enablesetfieldofview() const;
  void set_enablesetfieldofview(bool value);

  private:
  bool _internal_enablesetfieldofview() const;
  void _internal_set_enablesetfieldofview(bool value);

  public:
  // bool FixLowFovScene = 3;
  void clear_fixlowfovscene() ;
  bool fixlowfovscene() const;
  void set_fixlowfovscene(bool value);

  private:
  bool _internal_fixlowfovscene() const;
  void _internal_set_fixlowfovscene(bool value);

  public:
  // bool DisableFog = 4;
  void clear_disablefog() ;
  bool disablefog() const;
  void set_disablefog(bool value);

  private:
  bool _internal_disablefog() const;
  void _internal_set_disablefog(bool value);

  public:
  // bool EnableSetTargetFrameRate = 5;
  void clear_enablesettargetframerate() ;
  bool enablesettargetframerate() const;
  void set_enablesettargetframerate(bool value);

  private:
  bool _internal_enablesettargetframerate() const;
  void _internal_set_enablesettargetframerate(bool value);

  public:
  // int32 TargetFrameRate = 6;
  void clear_targetframerate() ;
  ::int32_t targetframerate() const;
  void set_targetframerate(::int32_t value);

  private:
  ::int32_t _internal_targetframerate() const;
  void _internal_set_targetframerate(::int32_t value);

  public:
  // bool RemoveOpenTeamProgress = 7;
  void clear_removeopenteamprogress() ;
  bool removeopenteamprogress() const;
  void set_removeopenteamprogress(bool value);

  private:
  bool _internal_removeopenteamprogress() const;
  void _internal_set_removeopenteamprogress(bool value);

  public:
  // bool HideQuestBanner = 8;
  void clear_hidequestbanner() ;
  bool hidequestbanner() const;
  void set_hidequestbanner(bool value);

  private:
  bool _internal_hidequestbanner() const;
  void _internal_set_hidequestbanner(bool value);

  public:
  // bool DisableEventCameraMove = 9;
  void clear_disableeventcameramove() ;
  bool disableeventcameramove() const;
  void set_disableeventcameramove(bool value);

  private:
  bool _internal_disableeventcameramove() const;
  void _internal_set_disableeventcameramove(bool value);

  public:
  // bool DisableShowDamageText = 10;
  void clear_disableshowdamagetext() ;
  bool disableshowdamagetext() const;
  void set_disableshowdamagetext(bool value);

  private:
  bool _internal_disableshowdamagetext() const;
  void _internal_set_disableshowdamagetext(bool value);

  public:
  // bool UsingTouchScreen = 11;
  void clear_usingtouchscreen() ;
  bool usingtouchscreen() const;
  void set_usingtouchscreen(bool value);

  private:
  bool _internal_usingtouchscreen() const;
  void _internal_set_usingtouchscreen(bool value);

  public:
  // bool RedirectCombineEntry = 12;
  void clear_redirectcombineentry() ;
  bool redirectcombineentry() const;
  void set_redirectcombineentry(bool value);

  private:
  bool _internal_redirectcombineentry() const;
  void _internal_set_redirectcombineentry(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Service.Proto.Island)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 13, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Island& from_msg);
    ::google::protobuf::internal::MapField<Island_ItemsEntry_DoNotUse, ::int32_t, bool,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>
        items_;
    float fieldofview_;
    bool enablesetfieldofview_;
    bool fixlowfovscene_;
    bool disablefog_;
    bool enablesettargetframerate_;
    ::int32_t targetframerate_;
    bool removeopenteamprogress_;
    bool hidequestbanner_;
    bool disableeventcameramove_;
    bool disableshowdamagetext_;
    bool usingtouchscreen_;
    bool redirectcombineentry_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_settings_2eproto;
};
// -------------------------------------------------------------------

class Home final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Service.Proto.Home) */ {
 public:
  inline Home() : Home(nullptr) {}
  ~Home() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Home* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Home));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Home(
      ::google::protobuf::internal::ConstantInitialized);

  inline Home(const Home& from) : Home(nullptr, from) {}
  inline Home(Home&& from) noexcept
      : Home(nullptr, std::move(from)) {}
  inline Home& operator=(const Home& from) {
    CopyFrom(from);
    return *this;
  }
  inline Home& operator=(Home&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Home& default_instance() {
    return *internal_default_instance();
  }
  static inline const Home* internal_default_instance() {
    return reinterpret_cast<const Home*>(
        &_Home_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Home& a, Home& b) { a.Swap(&b); }
  inline void Swap(Home* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Home* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Home* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Home>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Home& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Home& from) { Home::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Home* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Service.Proto.Home"; }

 protected:
  explicit Home(::google::protobuf::Arena* arena);
  Home(::google::protobuf::Arena* arena, const Home& from);
  Home(::google::protobuf::Arena* arena, Home&& from) noexcept
      : Home(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kGamePathFieldNumber = 1,
    kLaunchGameFieldNumber = 2,
    kIslandFieldNumber = 3,
    kSelectedIndexFieldNumber = 4,
  };
  // string GamePath = 1;
  void clear_gamepath() ;
  const std::string& gamepath() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_gamepath(Arg_&& arg, Args_... args);
  std::string* mutable_gamepath();
  PROTOBUF_NODISCARD std::string* release_gamepath();
  void set_allocated_gamepath(std::string* value);

  private:
  const std::string& _internal_gamepath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_gamepath(
      const std::string& value);
  std::string* _internal_mutable_gamepath();

  public:
  // .Service.Proto.LaunchGame LaunchGame = 2;
  bool has_launchgame() const;
  void clear_launchgame() ;
  const ::Service::Proto::LaunchGame& launchgame() const;
  PROTOBUF_NODISCARD ::Service::Proto::LaunchGame* release_launchgame();
  ::Service::Proto::LaunchGame* mutable_launchgame();
  void set_allocated_launchgame(::Service::Proto::LaunchGame* value);
  void unsafe_arena_set_allocated_launchgame(::Service::Proto::LaunchGame* value);
  ::Service::Proto::LaunchGame* unsafe_arena_release_launchgame();

  private:
  const ::Service::Proto::LaunchGame& _internal_launchgame() const;
  ::Service::Proto::LaunchGame* _internal_mutable_launchgame();

  public:
  // .Service.Proto.Island Island = 3;
  bool has_island() const;
  void clear_island() ;
  const ::Service::Proto::Island& island() const;
  PROTOBUF_NODISCARD ::Service::Proto::Island* release_island();
  ::Service::Proto::Island* mutable_island();
  void set_allocated_island(::Service::Proto::Island* value);
  void unsafe_arena_set_allocated_island(::Service::Proto::Island* value);
  ::Service::Proto::Island* unsafe_arena_release_island();

  private:
  const ::Service::Proto::Island& _internal_island() const;
  ::Service::Proto::Island* _internal_mutable_island();

  public:
  // int32 SelectedIndex = 4;
  void clear_selectedindex() ;
  ::int32_t selectedindex() const;
  void set_selectedindex(::int32_t value);

  private:
  ::int32_t _internal_selectedindex() const;
  void _internal_set_selectedindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Service.Proto.Home)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 2,
      35, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Home& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr gamepath_;
    ::Service::Proto::LaunchGame* launchgame_;
    ::Service::Proto::Island* island_;
    ::int32_t selectedindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_settings_2eproto;
};
// -------------------------------------------------------------------

class Settings final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Service.Proto.Settings) */ {
 public:
  inline Settings() : Settings(nullptr) {}
  ~Settings() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Settings* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Settings));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Settings(
      ::google::protobuf::internal::ConstantInitialized);

  inline Settings(const Settings& from) : Settings(nullptr, from) {}
  inline Settings(Settings&& from) noexcept
      : Settings(nullptr, std::move(from)) {}
  inline Settings& operator=(const Settings& from) {
    CopyFrom(from);
    return *this;
  }
  inline Settings& operator=(Settings&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Settings& default_instance() {
    return *internal_default_instance();
  }
  static inline const Settings* internal_default_instance() {
    return reinterpret_cast<const Settings*>(
        &_Settings_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(Settings& a, Settings& b) { a.Swap(&b); }
  inline void Swap(Settings* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Settings* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Settings* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Settings>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Settings& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Settings& from) { Settings::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Settings* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Service.Proto.Settings"; }

 protected:
  explicit Settings(::google::protobuf::Arena* arena);
  Settings(::google::protobuf::Arena* arena, const Settings& from);
  Settings(::google::protobuf::Arena* arena, Settings&& from) noexcept
      : Settings(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHomeFieldNumber = 1,
  };
  // .Service.Proto.Home Home = 1;
  bool has_home() const;
  void clear_home() ;
  const ::Service::Proto::Home& home() const;
  PROTOBUF_NODISCARD ::Service::Proto::Home* release_home();
  ::Service::Proto::Home* mutable_home();
  void set_allocated_home(::Service::Proto::Home* value);
  void unsafe_arena_set_allocated_home(::Service::Proto::Home* value);
  ::Service::Proto::Home* unsafe_arena_release_home();

  private:
  const ::Service::Proto::Home& _internal_home() const;
  ::Service::Proto::Home* _internal_mutable_home();

  public:
  // @@protoc_insertion_point(class_scope:Service.Proto.Settings)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Settings& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Service::Proto::Home* home_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_settings_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Home

// string GamePath = 1;
inline void Home::clear_gamepath() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gamepath_.ClearToEmpty();
}
inline const std::string& Home::gamepath() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Service.Proto.Home.GamePath)
  return _internal_gamepath();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Home::set_gamepath(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gamepath_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Service.Proto.Home.GamePath)
}
inline std::string* Home::mutable_gamepath() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_gamepath();
  // @@protoc_insertion_point(field_mutable:Service.Proto.Home.GamePath)
  return _s;
}
inline const std::string& Home::_internal_gamepath() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gamepath_.Get();
}
inline void Home::_internal_set_gamepath(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gamepath_.Set(value, GetArena());
}
inline std::string* Home::_internal_mutable_gamepath() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.gamepath_.Mutable( GetArena());
}
inline std::string* Home::release_gamepath() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Service.Proto.Home.GamePath)
  return _impl_.gamepath_.Release();
}
inline void Home::set_allocated_gamepath(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gamepath_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.gamepath_.IsDefault()) {
    _impl_.gamepath_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Service.Proto.Home.GamePath)
}

// .Service.Proto.LaunchGame LaunchGame = 2;
inline bool Home::has_launchgame() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.launchgame_ != nullptr);
  return value;
}
inline void Home::clear_launchgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.launchgame_ != nullptr) _impl_.launchgame_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Service::Proto::LaunchGame& Home::_internal_launchgame() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Service::Proto::LaunchGame* p = _impl_.launchgame_;
  return p != nullptr ? *p : reinterpret_cast<const ::Service::Proto::LaunchGame&>(::Service::Proto::_LaunchGame_default_instance_);
}
inline const ::Service::Proto::LaunchGame& Home::launchgame() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Service.Proto.Home.LaunchGame)
  return _internal_launchgame();
}
inline void Home::unsafe_arena_set_allocated_launchgame(::Service::Proto::LaunchGame* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.launchgame_);
  }
  _impl_.launchgame_ = reinterpret_cast<::Service::Proto::LaunchGame*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Service.Proto.Home.LaunchGame)
}
inline ::Service::Proto::LaunchGame* Home::release_launchgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Service::Proto::LaunchGame* released = _impl_.launchgame_;
  _impl_.launchgame_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Service::Proto::LaunchGame* Home::unsafe_arena_release_launchgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Service.Proto.Home.LaunchGame)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Service::Proto::LaunchGame* temp = _impl_.launchgame_;
  _impl_.launchgame_ = nullptr;
  return temp;
}
inline ::Service::Proto::LaunchGame* Home::_internal_mutable_launchgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.launchgame_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Service::Proto::LaunchGame>(GetArena());
    _impl_.launchgame_ = reinterpret_cast<::Service::Proto::LaunchGame*>(p);
  }
  return _impl_.launchgame_;
}
inline ::Service::Proto::LaunchGame* Home::mutable_launchgame() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Service::Proto::LaunchGame* _msg = _internal_mutable_launchgame();
  // @@protoc_insertion_point(field_mutable:Service.Proto.Home.LaunchGame)
  return _msg;
}
inline void Home::set_allocated_launchgame(::Service::Proto::LaunchGame* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.launchgame_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.launchgame_ = reinterpret_cast<::Service::Proto::LaunchGame*>(value);
  // @@protoc_insertion_point(field_set_allocated:Service.Proto.Home.LaunchGame)
}

// .Service.Proto.Island Island = 3;
inline bool Home::has_island() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.island_ != nullptr);
  return value;
}
inline void Home::clear_island() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.island_ != nullptr) _impl_.island_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::Service::Proto::Island& Home::_internal_island() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Service::Proto::Island* p = _impl_.island_;
  return p != nullptr ? *p : reinterpret_cast<const ::Service::Proto::Island&>(::Service::Proto::_Island_default_instance_);
}
inline const ::Service::Proto::Island& Home::island() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Service.Proto.Home.Island)
  return _internal_island();
}
inline void Home::unsafe_arena_set_allocated_island(::Service::Proto::Island* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.island_);
  }
  _impl_.island_ = reinterpret_cast<::Service::Proto::Island*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Service.Proto.Home.Island)
}
inline ::Service::Proto::Island* Home::release_island() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Service::Proto::Island* released = _impl_.island_;
  _impl_.island_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Service::Proto::Island* Home::unsafe_arena_release_island() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Service.Proto.Home.Island)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Service::Proto::Island* temp = _impl_.island_;
  _impl_.island_ = nullptr;
  return temp;
}
inline ::Service::Proto::Island* Home::_internal_mutable_island() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.island_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Service::Proto::Island>(GetArena());
    _impl_.island_ = reinterpret_cast<::Service::Proto::Island*>(p);
  }
  return _impl_.island_;
}
inline ::Service::Proto::Island* Home::mutable_island() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::Service::Proto::Island* _msg = _internal_mutable_island();
  // @@protoc_insertion_point(field_mutable:Service.Proto.Home.Island)
  return _msg;
}
inline void Home::set_allocated_island(::Service::Proto::Island* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.island_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.island_ = reinterpret_cast<::Service::Proto::Island*>(value);
  // @@protoc_insertion_point(field_set_allocated:Service.Proto.Home.Island)
}

// int32 SelectedIndex = 4;
inline void Home::clear_selectedindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selectedindex_ = 0;
}
inline ::int32_t Home::selectedindex() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Home.SelectedIndex)
  return _internal_selectedindex();
}
inline void Home::set_selectedindex(::int32_t value) {
  _internal_set_selectedindex(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Home.SelectedIndex)
}
inline ::int32_t Home::_internal_selectedindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.selectedindex_;
}
inline void Home::_internal_set_selectedindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selectedindex_ = value;
}

// -------------------------------------------------------------------

// LaunchGame

// bool UsingHoyolabAccount = 1;
inline void LaunchGame::clear_usinghoyolabaccount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.usinghoyolabaccount_ = false;
}
inline bool LaunchGame::usinghoyolabaccount() const {
  // @@protoc_insertion_point(field_get:Service.Proto.LaunchGame.UsingHoyolabAccount)
  return _internal_usinghoyolabaccount();
}
inline void LaunchGame::set_usinghoyolabaccount(bool value) {
  _internal_set_usinghoyolabaccount(value);
  // @@protoc_insertion_point(field_set:Service.Proto.LaunchGame.UsingHoyolabAccount)
}
inline bool LaunchGame::_internal_usinghoyolabaccount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.usinghoyolabaccount_;
}
inline void LaunchGame::_internal_set_usinghoyolabaccount(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.usinghoyolabaccount_ = value;
}

// bool AreCommandLineArgumentsEnabled = 2;
inline void LaunchGame::clear_arecommandlineargumentsenabled() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.arecommandlineargumentsenabled_ = false;
}
inline bool LaunchGame::arecommandlineargumentsenabled() const {
  // @@protoc_insertion_point(field_get:Service.Proto.LaunchGame.AreCommandLineArgumentsEnabled)
  return _internal_arecommandlineargumentsenabled();
}
inline void LaunchGame::set_arecommandlineargumentsenabled(bool value) {
  _internal_set_arecommandlineargumentsenabled(value);
  // @@protoc_insertion_point(field_set:Service.Proto.LaunchGame.AreCommandLineArgumentsEnabled)
}
inline bool LaunchGame::_internal_arecommandlineargumentsenabled() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.arecommandlineargumentsenabled_;
}
inline void LaunchGame::_internal_set_arecommandlineargumentsenabled(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.arecommandlineargumentsenabled_ = value;
}

// bool IsWindowsHDREnabled = 3;
inline void LaunchGame::clear_iswindowshdrenabled() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iswindowshdrenabled_ = false;
}
inline bool LaunchGame::iswindowshdrenabled() const {
  // @@protoc_insertion_point(field_get:Service.Proto.LaunchGame.IsWindowsHDREnabled)
  return _internal_iswindowshdrenabled();
}
inline void LaunchGame::set_iswindowshdrenabled(bool value) {
  _internal_set_iswindowshdrenabled(value);
  // @@protoc_insertion_point(field_set:Service.Proto.LaunchGame.IsWindowsHDREnabled)
}
inline bool LaunchGame::_internal_iswindowshdrenabled() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iswindowshdrenabled_;
}
inline void LaunchGame::_internal_set_iswindowshdrenabled(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iswindowshdrenabled_ = value;
}

// bool IsFullScreen = 4;
inline void LaunchGame::clear_isfullscreen() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isfullscreen_ = false;
}
inline bool LaunchGame::isfullscreen() const {
  // @@protoc_insertion_point(field_get:Service.Proto.LaunchGame.IsFullScreen)
  return _internal_isfullscreen();
}
inline void LaunchGame::set_isfullscreen(bool value) {
  _internal_set_isfullscreen(value);
  // @@protoc_insertion_point(field_set:Service.Proto.LaunchGame.IsFullScreen)
}
inline bool LaunchGame::_internal_isfullscreen() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isfullscreen_;
}
inline void LaunchGame::_internal_set_isfullscreen(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isfullscreen_ = value;
}

// bool IsExclusive = 5;
inline void LaunchGame::clear_isexclusive() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isexclusive_ = false;
}
inline bool LaunchGame::isexclusive() const {
  // @@protoc_insertion_point(field_get:Service.Proto.LaunchGame.IsExclusive)
  return _internal_isexclusive();
}
inline void LaunchGame::set_isexclusive(bool value) {
  _internal_set_isexclusive(value);
  // @@protoc_insertion_point(field_set:Service.Proto.LaunchGame.IsExclusive)
}
inline bool LaunchGame::_internal_isexclusive() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isexclusive_;
}
inline void LaunchGame::_internal_set_isexclusive(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isexclusive_ = value;
}

// bool IsBorderless = 6;
inline void LaunchGame::clear_isborderless() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isborderless_ = false;
}
inline bool LaunchGame::isborderless() const {
  // @@protoc_insertion_point(field_get:Service.Proto.LaunchGame.IsBorderless)
  return _internal_isborderless();
}
inline void LaunchGame::set_isborderless(bool value) {
  _internal_set_isborderless(value);
  // @@protoc_insertion_point(field_set:Service.Proto.LaunchGame.IsBorderless)
}
inline bool LaunchGame::_internal_isborderless() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isborderless_;
}
inline void LaunchGame::_internal_set_isborderless(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isborderless_ = value;
}

// bool IsScreenWidthEnabled = 7;
inline void LaunchGame::clear_isscreenwidthenabled() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isscreenwidthenabled_ = false;
}
inline bool LaunchGame::isscreenwidthenabled() const {
  // @@protoc_insertion_point(field_get:Service.Proto.LaunchGame.IsScreenWidthEnabled)
  return _internal_isscreenwidthenabled();
}
inline void LaunchGame::set_isscreenwidthenabled(bool value) {
  _internal_set_isscreenwidthenabled(value);
  // @@protoc_insertion_point(field_set:Service.Proto.LaunchGame.IsScreenWidthEnabled)
}
inline bool LaunchGame::_internal_isscreenwidthenabled() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isscreenwidthenabled_;
}
inline void LaunchGame::_internal_set_isscreenwidthenabled(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isscreenwidthenabled_ = value;
}

// int32 ScreenWidth = 8;
inline void LaunchGame::clear_screenwidth() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.screenwidth_ = 0;
}
inline ::int32_t LaunchGame::screenwidth() const {
  // @@protoc_insertion_point(field_get:Service.Proto.LaunchGame.ScreenWidth)
  return _internal_screenwidth();
}
inline void LaunchGame::set_screenwidth(::int32_t value) {
  _internal_set_screenwidth(value);
  // @@protoc_insertion_point(field_set:Service.Proto.LaunchGame.ScreenWidth)
}
inline ::int32_t LaunchGame::_internal_screenwidth() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.screenwidth_;
}
inline void LaunchGame::_internal_set_screenwidth(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.screenwidth_ = value;
}

// bool IsScreenHeightEnabled = 9;
inline void LaunchGame::clear_isscreenheightenabled() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isscreenheightenabled_ = false;
}
inline bool LaunchGame::isscreenheightenabled() const {
  // @@protoc_insertion_point(field_get:Service.Proto.LaunchGame.IsScreenHeightEnabled)
  return _internal_isscreenheightenabled();
}
inline void LaunchGame::set_isscreenheightenabled(bool value) {
  _internal_set_isscreenheightenabled(value);
  // @@protoc_insertion_point(field_set:Service.Proto.LaunchGame.IsScreenHeightEnabled)
}
inline bool LaunchGame::_internal_isscreenheightenabled() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isscreenheightenabled_;
}
inline void LaunchGame::_internal_set_isscreenheightenabled(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isscreenheightenabled_ = value;
}

// int32 ScreenHeight = 10;
inline void LaunchGame::clear_screenheight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.screenheight_ = 0;
}
inline ::int32_t LaunchGame::screenheight() const {
  // @@protoc_insertion_point(field_get:Service.Proto.LaunchGame.ScreenHeight)
  return _internal_screenheight();
}
inline void LaunchGame::set_screenheight(::int32_t value) {
  _internal_set_screenheight(value);
  // @@protoc_insertion_point(field_set:Service.Proto.LaunchGame.ScreenHeight)
}
inline ::int32_t LaunchGame::_internal_screenheight() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.screenheight_;
}
inline void LaunchGame::_internal_set_screenheight(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.screenheight_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Island

// bool EnableSetFieldOfView = 1;
inline void Island::clear_enablesetfieldofview() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enablesetfieldofview_ = false;
}
inline bool Island::enablesetfieldofview() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.EnableSetFieldOfView)
  return _internal_enablesetfieldofview();
}
inline void Island::set_enablesetfieldofview(bool value) {
  _internal_set_enablesetfieldofview(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.EnableSetFieldOfView)
}
inline bool Island::_internal_enablesetfieldofview() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enablesetfieldofview_;
}
inline void Island::_internal_set_enablesetfieldofview(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enablesetfieldofview_ = value;
}

// float FieldOfView = 2;
inline void Island::clear_fieldofview() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fieldofview_ = 0;
}
inline float Island::fieldofview() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.FieldOfView)
  return _internal_fieldofview();
}
inline void Island::set_fieldofview(float value) {
  _internal_set_fieldofview(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.FieldOfView)
}
inline float Island::_internal_fieldofview() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fieldofview_;
}
inline void Island::_internal_set_fieldofview(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fieldofview_ = value;
}

// bool FixLowFovScene = 3;
inline void Island::clear_fixlowfovscene() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fixlowfovscene_ = false;
}
inline bool Island::fixlowfovscene() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.FixLowFovScene)
  return _internal_fixlowfovscene();
}
inline void Island::set_fixlowfovscene(bool value) {
  _internal_set_fixlowfovscene(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.FixLowFovScene)
}
inline bool Island::_internal_fixlowfovscene() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fixlowfovscene_;
}
inline void Island::_internal_set_fixlowfovscene(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fixlowfovscene_ = value;
}

// bool DisableFog = 4;
inline void Island::clear_disablefog() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.disablefog_ = false;
}
inline bool Island::disablefog() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.DisableFog)
  return _internal_disablefog();
}
inline void Island::set_disablefog(bool value) {
  _internal_set_disablefog(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.DisableFog)
}
inline bool Island::_internal_disablefog() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.disablefog_;
}
inline void Island::_internal_set_disablefog(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.disablefog_ = value;
}

// bool EnableSetTargetFrameRate = 5;
inline void Island::clear_enablesettargetframerate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enablesettargetframerate_ = false;
}
inline bool Island::enablesettargetframerate() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.EnableSetTargetFrameRate)
  return _internal_enablesettargetframerate();
}
inline void Island::set_enablesettargetframerate(bool value) {
  _internal_set_enablesettargetframerate(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.EnableSetTargetFrameRate)
}
inline bool Island::_internal_enablesettargetframerate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enablesettargetframerate_;
}
inline void Island::_internal_set_enablesettargetframerate(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enablesettargetframerate_ = value;
}

// int32 TargetFrameRate = 6;
inline void Island::clear_targetframerate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targetframerate_ = 0;
}
inline ::int32_t Island::targetframerate() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.TargetFrameRate)
  return _internal_targetframerate();
}
inline void Island::set_targetframerate(::int32_t value) {
  _internal_set_targetframerate(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.TargetFrameRate)
}
inline ::int32_t Island::_internal_targetframerate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.targetframerate_;
}
inline void Island::_internal_set_targetframerate(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.targetframerate_ = value;
}

// bool RemoveOpenTeamProgress = 7;
inline void Island::clear_removeopenteamprogress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.removeopenteamprogress_ = false;
}
inline bool Island::removeopenteamprogress() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.RemoveOpenTeamProgress)
  return _internal_removeopenteamprogress();
}
inline void Island::set_removeopenteamprogress(bool value) {
  _internal_set_removeopenteamprogress(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.RemoveOpenTeamProgress)
}
inline bool Island::_internal_removeopenteamprogress() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.removeopenteamprogress_;
}
inline void Island::_internal_set_removeopenteamprogress(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.removeopenteamprogress_ = value;
}

// bool HideQuestBanner = 8;
inline void Island::clear_hidequestbanner() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hidequestbanner_ = false;
}
inline bool Island::hidequestbanner() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.HideQuestBanner)
  return _internal_hidequestbanner();
}
inline void Island::set_hidequestbanner(bool value) {
  _internal_set_hidequestbanner(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.HideQuestBanner)
}
inline bool Island::_internal_hidequestbanner() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hidequestbanner_;
}
inline void Island::_internal_set_hidequestbanner(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hidequestbanner_ = value;
}

// bool DisableEventCameraMove = 9;
inline void Island::clear_disableeventcameramove() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.disableeventcameramove_ = false;
}
inline bool Island::disableeventcameramove() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.DisableEventCameraMove)
  return _internal_disableeventcameramove();
}
inline void Island::set_disableeventcameramove(bool value) {
  _internal_set_disableeventcameramove(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.DisableEventCameraMove)
}
inline bool Island::_internal_disableeventcameramove() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.disableeventcameramove_;
}
inline void Island::_internal_set_disableeventcameramove(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.disableeventcameramove_ = value;
}

// bool DisableShowDamageText = 10;
inline void Island::clear_disableshowdamagetext() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.disableshowdamagetext_ = false;
}
inline bool Island::disableshowdamagetext() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.DisableShowDamageText)
  return _internal_disableshowdamagetext();
}
inline void Island::set_disableshowdamagetext(bool value) {
  _internal_set_disableshowdamagetext(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.DisableShowDamageText)
}
inline bool Island::_internal_disableshowdamagetext() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.disableshowdamagetext_;
}
inline void Island::_internal_set_disableshowdamagetext(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.disableshowdamagetext_ = value;
}

// bool UsingTouchScreen = 11;
inline void Island::clear_usingtouchscreen() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.usingtouchscreen_ = false;
}
inline bool Island::usingtouchscreen() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.UsingTouchScreen)
  return _internal_usingtouchscreen();
}
inline void Island::set_usingtouchscreen(bool value) {
  _internal_set_usingtouchscreen(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.UsingTouchScreen)
}
inline bool Island::_internal_usingtouchscreen() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.usingtouchscreen_;
}
inline void Island::_internal_set_usingtouchscreen(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.usingtouchscreen_ = value;
}

// bool RedirectCombineEntry = 12;
inline void Island::clear_redirectcombineentry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redirectcombineentry_ = false;
}
inline bool Island::redirectcombineentry() const {
  // @@protoc_insertion_point(field_get:Service.Proto.Island.RedirectCombineEntry)
  return _internal_redirectcombineentry();
}
inline void Island::set_redirectcombineentry(bool value) {
  _internal_set_redirectcombineentry(value);
  // @@protoc_insertion_point(field_set:Service.Proto.Island.RedirectCombineEntry)
}
inline bool Island::_internal_redirectcombineentry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.redirectcombineentry_;
}
inline void Island::_internal_set_redirectcombineentry(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.redirectcombineentry_ = value;
}

// map<int32, bool> items = 13;
inline int Island::_internal_items_size() const {
  return _internal_items().size();
}
inline int Island::items_size() const {
  return _internal_items_size();
}
inline void Island::clear_items() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_.Clear();
}
inline const ::google::protobuf::Map<::int32_t, bool>& Island::_internal_items() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.items_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, bool>& Island::items() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:Service.Proto.Island.items)
  return _internal_items();
}
inline ::google::protobuf::Map<::int32_t, bool>* Island::_internal_mutable_items() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.items_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, bool>* Island::mutable_items() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:Service.Proto.Island.items)
  return _internal_mutable_items();
}

// -------------------------------------------------------------------

// Settings

// .Service.Proto.Home Home = 1;
inline bool Settings::has_home() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.home_ != nullptr);
  return value;
}
inline void Settings::clear_home() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.home_ != nullptr) _impl_.home_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Service::Proto::Home& Settings::_internal_home() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Service::Proto::Home* p = _impl_.home_;
  return p != nullptr ? *p : reinterpret_cast<const ::Service::Proto::Home&>(::Service::Proto::_Home_default_instance_);
}
inline const ::Service::Proto::Home& Settings::home() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Service.Proto.Settings.Home)
  return _internal_home();
}
inline void Settings::unsafe_arena_set_allocated_home(::Service::Proto::Home* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.home_);
  }
  _impl_.home_ = reinterpret_cast<::Service::Proto::Home*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Service.Proto.Settings.Home)
}
inline ::Service::Proto::Home* Settings::release_home() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Service::Proto::Home* released = _impl_.home_;
  _impl_.home_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Service::Proto::Home* Settings::unsafe_arena_release_home() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Service.Proto.Settings.Home)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Service::Proto::Home* temp = _impl_.home_;
  _impl_.home_ = nullptr;
  return temp;
}
inline ::Service::Proto::Home* Settings::_internal_mutable_home() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.home_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Service::Proto::Home>(GetArena());
    _impl_.home_ = reinterpret_cast<::Service::Proto::Home*>(p);
  }
  return _impl_.home_;
}
inline ::Service::Proto::Home* Settings::mutable_home() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Service::Proto::Home* _msg = _internal_mutable_home();
  // @@protoc_insertion_point(field_mutable:Service.Proto.Settings.Home)
  return _msg;
}
inline void Settings::set_allocated_home(::Service::Proto::Home* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.home_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.home_ = reinterpret_cast<::Service::Proto::Home*>(value);
  // @@protoc_insertion_point(field_set_allocated:Service.Proto.Settings.Home)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
}  // namespace Service


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // settings_2eproto_2epb_2eh
